# Generated by Django 6.0.2 on 2026-03-01 05:43

import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('twitch_user_id', models.CharField(max_length=50, unique=True)),
                ('twitch_username', models.CharField(max_length=100)),
                ('access_token', encrypted_fields.fields.EncryptedTextField(blank=True, default='')),
                ('refresh_token', encrypted_fields.fields.EncryptedTextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_channel_id', models.CharField(max_length=50)),
                ('twitch_channel_name', models.CharField(max_length=100)),
                ('owner_access_token', encrypted_fields.fields.EncryptedTextField(blank=True, default='')),
                ('owner_refresh_token', encrypted_fields.fields.EncryptedTextField(blank=True, default='')),
                ('owner_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='core.bot')),
            ],
            options={
                'unique_together': {('bot', 'twitch_channel_id')},
            },
        ),
        migrations.CreateModel(
            name='CodedCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coded_commands', to='core.channel')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('channel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('response', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('cooldown_seconds', models.PositiveIntegerField(default=0)),
                ('user_cooldown_seconds', models.PositiveIntegerField(default=0)),
                ('mod_only', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='core.channel')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('channel', 'name')},
            },
        ),
    ]
