# Generated by Django 6.0.2 on 2026-03-01 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=200)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.channel')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('channel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('value', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='core.channel')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('channel', 'name')},
            },
        ),
    ]
