# Generated by Django 6.0.2 on 2026-03-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_migrate_variable_syntax'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='command',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('lottery', 'Lottery'), ('random_list', 'Random List'), ('counter', 'Counter')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='command',
            name='response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
