# Generated by Django 6.0.2 on 2026-03-18 04:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_skillstat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twitch_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('twitch_username', models.CharField(max_length=100)),
                ('twitch_display_name', models.CharField(max_length=100)),
                ('twitch_avatar', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twitch_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
